language: node_js
node_js:
- 5
- 6
addons:
    code_climate:
        repo_token: 5be0d4bf8a63e47f7cf2e15071d850e76171376fb761023ce15798b39537615c
script:
    yarn run coverage
after_success:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: ikerin@gmail.com
  api_key:
    secure: bfF8eBdUQ8giBLe6QIRZuXZ/+/neTgbYGldhWLP1xcLUB115EriUmcjRXHN+hAXozM7bYZI6mp+CPXH85L4Y9GveMiWjuedCFp35FvdnZWM+wT4tE7teVXoyt8cWuoktE0Ii/jFEJMiRZbbnFIwfo17jeUxSjAauQzsM4DmBI8ydHsk7eLGoEpmB3Y26Oj9aAb+LgqFWOZyB3J1wS0IvpWhn692zvmH49vShbVNzrdTpRFe2pdbMp8kwHmogZ7R43ss9Yeb7B5r+kI9J0MlQsuGM8yXejdQ/B26gQx4ORHl8qYYiDyY15OCypTgSbpktxwzT40yVp0NQOUw+cy51QgDJsNLKt/Tj7Yz/KJGo8brXM7W381ZlNKGbOsZXiZAQcQ7/dl8I1TtRJ+W0hmFTWHdk/FE9XCNm8kQJDM1Vbp5sTvDaZQafL+IvjaZu75PVgLdUnB0aMyJJfBFAci9oeSczuKtBB5uYCyY/0jCe/wv7Gex+DUpZBu6qlAB+VvqFnMAjWHnWuAu5W1vyLpqyKwF4zE74EzikGqLIna3+82B6m9KZrNXRVhWJtAMvsvzXXLUMZ4Eez6bmXuErSFPTvAO0IVEbjy9PDw9zJk1xYwrPQCwpuHN2ytBYbFmx4+vmJiuq+dR8jVQuZZpq64GpXU9LDXhxQ28ZqYlXEtuU/VU=
  on:
    tags: true
    repo: enhancv/braintree-as-promised
notifications:
  email: false
  slack:
    secure: XqgxnW5T3FVpBLUQU776Xnn7pPV3w6N+BVcxXY33Wwh4YXlaBsfJcq9JGovkYbzPnrpW55qRKtWAl2K6Gau95Vn78A6S630uYmTf8ET9TZOluiiX+WfeSKXrFAi/z23Fv4RaAkoBRDpmvwAoUlk8muruhiSUbfph/HRzZKLvmDxOESAVyobqFPsWirQ5Bz6euObRLOlAjTCciX+d01AdlAuQ61nD6Dn6d6ZuxXyafpL+yYM3nbNkPr2x90w5sQySdbvvA7uttNskvmTWqLnb+GOebTCfSVyDL4UkGVQc64kcwuO/eJ8CnM56xr7RzSfShr6SFGQ91vbzK6FJBJBocA5lJS0xJSt9sXcSKHok0IW5mJibaYjIqhelTrq98VF/EXV7oyrC5lxQD8i+WYhohAPA1ufaFYDdkOQDHVz+FBQkwIBCgl7Qd4oYKRRbE85nctS/2ipjZC1NdxPNSC8eID5MZc1v4czohX9qLBBA7XXWr3f/dmxxVECNCG0EmijTXadyrspAvt+tHzY7m3G9wQzbObmcUjP68jh91pK3vtlJmf8vtleCqZCS+J2nI3LvjSFpedFqwl7MugJXE45eLdAHPMTkk2wreGGM9G8vL2xrvWPxY2nrxReu6OtHQJzQXtvtkMiGwH/79Ow7EZvN7jtQAX+R/+5gy7jHVKs49zo=
