language: node_js
node_js:
  - 5
  - 4
before_script:
  - npm install codacy-coverage mocha-lcov-reporter
script:
  - node_modules/.bin/eslint {src,test}
  - node_modules/.bin/istanbul cover node_modules/.bin/_mocha --report lcovonly -- -R spec
after_script:
  - cat coverage/lcov.info | node_modules/.bin/codacy-coverage
